// src/ClassifiedAds.UIs/angular/src/app/products/add-product/add-product.component.ts
import { Component, OnInit } from "@angular/core";
import { IProduct } from "../product";
import { NgModel, NgForm } from "@angular/forms";
import { ProductService } from "../product.service";
import { Router } from "@angular/router";

@Component({
  templateUrl: "./add-product.component.html",
  styleUrls: ["./add-product.component.css"]
})
export class AddProductComponent implements OnInit {
  product: IProduct = {
    id: "00000000-0000-0000-0000-000000000000",
    name: null,
    code: null,
    description: null,
    imageUrl: null,
    price: null,
    releaseDate: null,
    starRating: null
  };
  postErrorMessage: string = "";
  postError = false;

  constructor(private productService: ProductService, private router: Router) {}

  ngOnInit(): void {}

  onBlur(field: NgModel) {
    console.log("in onBlur: ", field.valid);
  }

  onSubmit(form: NgForm) {
    console.log("in onSubmit: ", form.value, this.product);

    if (form.valid) {
      this.productService.addProduct(this.product).subscribe(
        result => {
          console.log("success: ", result);
          this.router.navigate(["/products", result.id]);
        },
        error => this.onHttpError(error)
      );
    } else {
      this.postError = true;
      this.postErrorMessage = "Please fix the errors";
    }
  }

  onHttpError(errorResponse: any) {
    console.log("error: ", errorResponse);
    this.postError = true;
    this.postErrorMessage = errorResponse.error.errorMessage;
  }
}

<div class="card">
  <div class="card-header">
    Add Product
  </div>
  <div class="card-body">
    <div class="row" [hidden]="!postError" class="alert alert-danger">
      {{ postErrorMessage }}
    </div>
    <form #form="ngForm" (ngSubmit)="onSubmit(form)">
      <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
          <input
            id="name"
            name="name"
            class="form-control"
            [(ngModel)]="product.name"
            required
            #nameField="ngModel"
            (blur)="onBlur(nameField)"
            [class.field-error]="form.submitted && nameField.invalid"
          />
          <div
            [hidden]="!form.submitted || nameField.valid"
            class="alert alert-danger"
          >
            Enter a name
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="code" class="col-sm-2 col-form-label">Code</label>
        <div class="col-sm-10">
          <input
            id="code"
            name="code"
            class="form-control"
            [(ngModel)]="product.code"
            required
            #codeField="ngModel"
            (blur)="onBlur(codeField)"
            [class.field-error]="form.submitted && codeField.invalid"
          />
          <div
            [hidden]="!form.submitted || codeField.valid"
            class="alert alert-danger"
          >
            Enter a code
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label"
          >Description</label
        >
        <div class="col-sm-10">
          <input
            id="description"
            name="description"
            class="form-control"
            [(ngModel)]="product.description"
            required
            #descriptionField="ngModel"
            (blur)="onBlur(descriptionField)"
            [class.field-error]="form.submitted && descriptionField.invalid"
          />
          <div
            [hidden]="!form.submitted || descriptionField.valid"
            class="alert alert-danger"
          >
            Enter a description
          </div>
        </div>
      </div>
      <div class="form-group row">
        <label for="description" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
          <button class="btn btn-primary">Save</button>
        </div>
      </div>
    </form>
  </div>
  <div class="card-footer">
    <a
      class="btn btn-outline-secondary"
      [routerLink]="['/products']"
      style="width:80px"
    >
      <i class="fa fa-chevron-left"></i> Back
    </a>
  </div>
</div>

// src/ClassifiedAds.UIs/reactjs/src/containers/Products/AddProduct/AddProduct.js
import React, { Component } from "react";
import { NavLink, Redirect } from "react-router-dom";
import { connect } from "react-redux";

import * as actions from "../actions";

class AddProduct extends Component {
  state = {
    title: "Add Product",
    submitted: false,
    errorMessage: null
  };

  componentDidMount() {
    this.props.resetProduct();
    const id = this.props.match?.params?.id;
    if (id) {
      this.setState({ title: "Edit Product" });
      this.props.fetchProduct(id);
    }
  }

  fieldChanged = event => {
    const product = {
      ...this.props.product,
      [event.target.name]: event.target.value
    };
    this.props.updateProduct(product);
  };

  onSubmit = event => {
    event.preventDefault();
    this.setState({ submitted: true });
    this.props.saveProduct(this.props.product);
  };

  render() {
    const form = (
      <div className="card">
        <div className="card-header">{this.state.title}</div>
        <div className="card-body">
          {this.state.errorMessage ? (
            <div
              className="row"
              hidden="!postError"
              className="alert alert-danger"
            >
              {this.state.errorMessage}
            </div>
          ) : null}
          <form onSubmit={this.onSubmit}>
            <div className="form-group row">
              <label htmlFor="name" className="col-sm-2 col-form-label">
                Name
              </label>
              <div className="col-sm-10">
                <input
                  id="name"
                  name="name"
                  className="form-control"
                  value={this.props.product?.name}
                  onChange={event => this.fieldChanged(event)}
                  required
                />
                <span className="invalid-feedback">Enter a name</span>
              </div>
            </div>
            <div className="form-group row">
              <label htmlFor="code" className="col-sm-2 col-form-label">
                Code
              </label>
              <div className="col-sm-10">
                <input
                  id="code"
                  name="code"
                  className="form-control"
                  value={this.props.product?.code}
                  onChange={event => this.fieldChanged(event)}
                  required
                />
                <span className="invalid-feedback">Enter a code</span>
              </div>
            </div>
            <div className="form-group row">
              <label htmlFor="description" className="col-sm-2 col-form-label">
                Description
              </label>
              <div className="col-sm-10">
                <input
                  id="description"
                  name="description"
                  className="form-control"
                  value={this.props.product?.description}
                  onChange={event => this.fieldChanged(event)}
                  required
                />
                <span className="invalid-feedback">Enter a description</span>
              </div>
            </div>
            <div className="form-group row">
              <label
                htmlFor="description"
                className="col-sm-2 col-form-label"
              ></label>
              <div className="col-sm-10">
                <button className="btn btn-primary">Save</button>
              </div>
            </div>
          </form>
        </div>
        <div className="card-footer">
          <NavLink
            className="btn btn-outline-secondary"
            to="/products"
            style={{ width: "80px" }}
          >
            <i className="fa fa-chevron-left"></i> Back
          </NavLink>
        </div>
      </div>
    );

    return this.state.submitted && this.props.saved ? (
      <Redirect to={"/products/" + this.props.product.id} />
    ) : (
      form
    );
  }
}

const mapStateToProps = state => {
  return {
    product: state.product.product,
    saved: state.product.saved
  };
};

const mapDispatchToProps = dispatch => {
  return {
    fetchProduct: id => dispatch(actions.fetchProduct(id)),
    updateProduct: product => dispatch(actions.updateProduct(product)),
    resetProduct: () => dispatch(actions.resetProduct()),
    saveProduct: product => dispatch(actions.saveProduct(product))
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(AddProduct);
