// src/ClassifiedAds.UIs/vuejs/src/views/Nav.vue
<template>
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="/">{{ pageTitle | appendVersion }}</a>
    <ul class="nav nav-pills">
      <li>
        <router-link class="nav-link" to="/" active-class="active" exact>Home</router-link>
      </li>
      <li>
        <router-link class="nav-link" to="/products" active-class="active">Product</router-link>
      </li>
      <li v-if="!isAuthenticated">
        <a class="nav-link" @click="login" href="javascript:void(0)">Login</a>
      </li>
      <li v-if="isAuthenticated">
        <a class="nav-link" @click="logout" href="javascript:void(0)">Logout</a>
      </li>
    </ul>
  </nav>
</template>

<script>
export default {
  data() {
    return { pageTitle: "ClassifiedAds.Vue", isAuthenticated: false };
  },
  methods: {
    login() {},
    logout() {}
  }
};
</script>

<style scoped>
.nav-link {
  font-size: large;
}
</style>

// src/ClassifiedAds.UIs/reactjs/src/components/Nav/Nav.js
import React from "react";
import { NavLink } from "react-router-dom";

import classes from "./Nav.module.css";

const Nav = props => {
  const pageTitle = "ClassifiedAds.React";
  return (
    <nav
      className={"navbar navbar-expand navbar-light bg-light " + classes.Nav}
    >
      <a className="navbar-brand" href="/">
        {pageTitle + " " + React.version}
      </a>
      <ul className="nav nav-pills">
        <li>
          <NavLink className="nav-link" to="/home">
            Home
          </NavLink>
        </li>

        <li>
          <NavLink className="nav-link" to="/products">
            Product
          </NavLink>
        </li>

        {!props.isAuthenticated ? (
          <li>
            <NavLink
              className="nav-link"
              to="/login"
              click="login()"
              href="javascript:void(0)"
            >
              Login
            </NavLink>
          </li>
        ) : null}

        {props.isAuthenticated ? (
          <li>
            <NavLink
              className="nav-link"
              to="/logout"
              click="logout()"
              href="javascript:void(0)"
            >
              Logout
            </NavLink>
          </li>
        ) : null}
      </ul>
    </nav>
  );
};

export default Nav;
